// Dữ liệu mẫu cho Bài tập Hóa 11 - Chương 1: Sự điện li
// Chủ đề: Chất điện li - chất không điện li. Axit, bazơ và muối

export const sampleExercises = [
  {
    title: 'Bài 1: Khái niệm về sự điện li',
    description: 'Bài tập nhận biết về chất điện li và chất không điện li',
    chapter: 'Chương 1',
    topic: 'Chất điện li - chất không điện li',
    lessonNumber: 1,
    exerciseType: 'bai-tap-nhan-biet',
    timeLimit: 20,
    passingScore: 5,
    questions: [
      {
        content: 'Chất nào sau đây là chất điện li?',
        questionType: 'multiple-choice',
        difficulty: 'easy',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'NaCl', isCorrect: true },
          { optionLabel: 'B', content: 'C6H12O6 (glucozơ)', isCorrect: false },
          { optionLabel: 'C', content: 'C2H5OH (etanol)', isCorrect: false },
          { optionLabel: 'D', content: 'C12H22O11 (saccarozơ)', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'NaCl là muối tan, khi tan trong nước phân li thành ion Na⁺ và Cl⁻ nên là chất điện li.',
      },
      {
        content: 'Dung dịch nào sau đây dẫn điện tốt nhất?',
        questionType: 'multiple-choice',
        difficulty: 'medium',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'Dung dịch HCl', isCorrect: true },
          { optionLabel: 'B', content: 'Dung dịch CH3COOH', isCorrect: false },
          { optionLabel: 'C', content: 'Dung dịch C2H5OH', isCorrect: false },
          { optionLabel: 'D', content: 'Dung dịch glucozơ', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'HCl là axit mạnh, phân li hoàn toàn trong nước tạo nhiều ion nên dẫn điện tốt nhất.',
      },
      {
        content: 'Chất không điện li là chất:',
        questionType: 'multiple-choice',
        difficulty: 'easy',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'Tan trong nước nhưng không phân li thành ion', isCorrect: true },
          { optionLabel: 'B', content: 'Không tan trong nước', isCorrect: false },
          { optionLabel: 'C', content: 'Phân li một phần trong nước', isCorrect: false },
          { optionLabel: 'D', content: 'Phân li hoàn toàn trong nước', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'Chất không điện li là chất khi tan trong nước không phân li thành ion.',
      },
      {
        content: 'Phát biểu nào sau đây đúng về chất điện li mạnh?',
        questionType: 'multiple-choice',
        difficulty: 'medium',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'Là chất phân li hoàn toàn thành ion trong nước', isCorrect: true },
          { optionLabel: 'B', content: 'Là chất phân li một phần thành ion trong nước', isCorrect: false },
          { optionLabel: 'C', content: 'Là chất không phân li trong nước', isCorrect: false },
          { optionLabel: 'D', content: 'Là chất không tan trong nước', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'Chất điện li mạnh là chất khi tan trong nước, các phân tử hòa tan đều phân li thành ion.',
      },
      {
        content: 'Cho các chất: HCl, H2SO4, CH3COOH, NaOH, NH3, NaCl. Số chất điện li mạnh là:',
        questionType: 'multiple-choice',
        difficulty: 'medium',
        points: 1,
        answers: [
          { optionLabel: 'A', content: '3', isCorrect: false },
          { optionLabel: 'B', content: '4', isCorrect: true },
          { optionLabel: 'C', content: '5', isCorrect: false },
          { optionLabel: 'D', content: '6', isCorrect: false },
        ],
        correctAnswer: 'B',
        explanation: 'Các chất điện li mạnh là: HCl, H2SO4, NaOH, NaCl (4 chất). CH3COOH và NH3 là chất điện li yếu.',
      },
    ],
  },
  {
    title: 'Bài 2: Axit - Bazơ - Muối',
    description: 'Bài tập về định nghĩa và tính chất của axit, bazơ, muối',
    chapter: 'Chương 1',
    topic: 'Axit, bazơ và muối',
    lessonNumber: 2,
    exerciseType: 'bai-tap-thong-hieu',
    timeLimit: 25,
    passingScore: 5,
    questions: [
      {
        content: 'Theo thuyết Arrheniut, axit là chất khi tan trong nước:',
        questionType: 'multiple-choice',
        difficulty: 'easy',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'Phân li ra cation H⁺', isCorrect: true },
          { optionLabel: 'B', content: 'Phân li ra anion OH⁻', isCorrect: false },
          { optionLabel: 'C', content: 'Không phân li thành ion', isCorrect: false },
          { optionLabel: 'D', content: 'Phân li ra cả H⁺ và OH⁻', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'Theo Arrheniut, axit là chất khi tan trong nước phân li ra cation H⁺.',
      },
      {
        content: 'Bazơ là hợp chất khi tan trong nước cho:',
        questionType: 'multiple-choice',
        difficulty: 'easy',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'Cation H⁺', isCorrect: false },
          { optionLabel: 'B', content: 'Anion OH⁻', isCorrect: true },
          { optionLabel: 'C', content: 'Cả H⁺ và OH⁻', isCorrect: false },
          { optionLabel: 'D', content: 'Không có ion nào', isCorrect: false },
        ],
        correctAnswer: 'B',
        explanation: 'Bazơ là hợp chất khi tan trong nước phân li ra anion OH⁻.',
      },
      {
        content: 'Muối là hợp chất:',
        questionType: 'multiple-choice',
        difficulty: 'easy',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'Gồm cation kim loại và anion gốc axit', isCorrect: true },
          { optionLabel: 'B', content: 'Chỉ có cation kim loại', isCorrect: false },
          { optionLabel: 'C', content: 'Chỉ có anion gốc axit', isCorrect: false },
          { optionLabel: 'D', content: 'Không có ion', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'Muối là hợp chất mà phân tử gồm cation kim loại (hoặc NH4⁺) liên kết với anion gốc axit.',
      },
      {
        content: 'Phương trình điện li nào sau đây đúng?',
        questionType: 'multiple-choice',
        difficulty: 'medium',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'HCl → H⁺ + Cl⁻', isCorrect: true },
          { optionLabel: 'B', content: 'HCl ⇌ H⁺ + Cl⁻', isCorrect: false },
          { optionLabel: 'C', content: 'HCl → 2H⁺ + Cl⁻', isCorrect: false },
          { optionLabel: 'D', content: 'HCl → H₂⁺ + Cl⁻', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'HCl là axit mạnh nên phân li hoàn toàn, dùng mũi tên một chiều (→).',
      },
      {
        content: 'Axit nào sau đây là axit yếu?',
        questionType: 'multiple-choice',
        difficulty: 'medium',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'HCl', isCorrect: false },
          { optionLabel: 'B', content: 'HNO3', isCorrect: false },
          { optionLabel: 'C', content: 'H2SO4', isCorrect: false },
          { optionLabel: 'D', content: 'CH3COOH', isCorrect: true },
        ],
        correctAnswer: 'D',
        explanation: 'CH3COOH (axit axetic) là axit yếu, phân li không hoàn toàn trong nước.',
      },
      {
        content: 'Dung dịch NaOH có pH:',
        questionType: 'multiple-choice',
        difficulty: 'easy',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'pH < 7', isCorrect: false },
          { optionLabel: 'B', content: 'pH = 7', isCorrect: false },
          { optionLabel: 'C', content: 'pH > 7', isCorrect: true },
          { optionLabel: 'D', content: 'pH = 0', isCorrect: false },
        ],
        correctAnswer: 'C',
        explanation: 'NaOH là bazơ mạnh nên dung dịch có pH > 7.',
      },
      {
        content: 'Cho các chất: HCl, NaOH, NaCl, H2SO4, Ca(OH)2, KNO3. Số chất là muối là:',
        questionType: 'multiple-choice',
        difficulty: 'medium',
        points: 1,
        answers: [
          { optionLabel: 'A', content: '1', isCorrect: false },
          { optionLabel: 'B', content: '2', isCorrect: true },
          { optionLabel: 'C', content: '3', isCorrect: false },
          { optionLabel: 'D', content: '4', isCorrect: false },
        ],
        correctAnswer: 'B',
        explanation: 'Các muối là: NaCl và KNO3 (2 chất).',
      },
    ],
  },
  {
    title: 'Bài 3: Phản ứng trao đổi ion',
    description: 'Bài tập về điều kiện xảy ra phản ứng trao đổi ion trong dung dịch',
    chapter: 'Chương 1',
    topic: 'Phản ứng trao đổi ion trong dung dịch chất điện li',
    lessonNumber: 3,
    exerciseType: 'bai-tap-van-dung',
    timeLimit: 30,
    passingScore: 6,
    questions: [
      {
        content: 'Phản ứng trao đổi ion trong dung dịch các chất điện li xảy ra khi:',
        questionType: 'multiple-choice',
        difficulty: 'medium',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'Có ít nhất một trong các ion kết hợp với nhau tạo thành chất kết tủa, chất khí hoặc chất điện li yếu', isCorrect: true },
          { optionLabel: 'B', content: 'Có tất cả các ion kết hợp với nhau', isCorrect: false },
          { optionLabel: 'C', content: 'Không có ion nào kết hợp', isCorrect: false },
          { optionLabel: 'D', content: 'Chỉ tạo chất kết tủa', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'Phản ứng trao đổi ion xảy ra khi có ít nhất một sản phẩm là chất kết tủa, chất khí hoặc chất điện li yếu.',
      },
      {
        content: 'Phương trình ion rút gọn nào sau đây đúng cho phản ứng: HCl + NaOH → NaCl + H2O',
        questionType: 'multiple-choice',
        difficulty: 'medium',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'H⁺ + OH⁻ → H2O', isCorrect: true },
          { optionLabel: 'B', content: 'Na⁺ + Cl⁻ → NaCl', isCorrect: false },
          { optionLabel: 'C', content: 'HCl + NaOH → NaCl + H2O', isCorrect: false },
          { optionLabel: 'D', content: 'H⁺ + Cl⁻ → HCl', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'Phương trình ion rút gọn chỉ viết các ion tham gia phản ứng: H⁺ + OH⁻ → H2O',
      },
      {
        content: 'Cặp chất nào sau đây không xảy ra phản ứng trao đổi ion?',
        questionType: 'multiple-choice',
        difficulty: 'medium',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'NaCl và KNO3', isCorrect: true },
          { optionLabel: 'B', content: 'HCl và AgNO3', isCorrect: false },
          { optionLabel: 'C', content: 'NaOH và H2SO4', isCorrect: false },
          { optionLabel: 'D', content: 'BaCl2 và Na2SO4', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'NaCl và KNO3 không tạo chất kết tủa, chất khí hay chất điện li yếu nên không xảy ra phản ứng.',
      },
      {
        content: 'Cho phương trình: AgNO3 + HCl → AgCl↓ + HNO3. Phương trình ion rút gọn là:',
        questionType: 'multiple-choice',
        difficulty: 'hard',
        points: 2,
        answers: [
          { optionLabel: 'A', content: 'Ag⁺ + Cl⁻ → AgCl↓', isCorrect: true },
          { optionLabel: 'B', content: 'AgNO3 + Cl⁻ → AgCl↓ + NO3⁻', isCorrect: false },
          { optionLabel: 'C', content: 'Ag⁺ + HCl → AgCl↓ + H⁺', isCorrect: false },
          { optionLabel: 'D', content: 'AgNO3 + HCl → AgCl↓ + HNO3', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'Chỉ có ion Ag⁺ và Cl⁻ tham gia phản ứng tạo kết tủa AgCl.',
      },
      {
        content: 'Dung dịch nào sau đây tác dụng được với dung dịch BaCl2 tạo kết tủa trắng?',
        questionType: 'multiple-choice',
        difficulty: 'medium',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'Na2SO4', isCorrect: true },
          { optionLabel: 'B', content: 'NaCl', isCorrect: false },
          { optionLabel: 'C', content: 'KNO3', isCorrect: false },
          { optionLabel: 'D', content: 'HCl', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'Na2SO4 + BaCl2 → BaSO4↓ (trắng) + 2NaCl',
      },
    ],
  },
  {
    title: 'Đề kiểm tra 15 phút - Chương 1',
    description: 'Đề kiểm tra tổng hợp kiến thức chương 1',
    chapter: 'Chương 1',
    topic: 'Ôn tập chương 1',
    exerciseType: 'de-kiem-tra',
    timeLimit: 15,
    passingScore: 5,
    questions: [
      {
        content: 'Chất nào sau đây là chất điện li yếu?',
        questionType: 'multiple-choice',
        difficulty: 'easy',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'HCl', isCorrect: false },
          { optionLabel: 'B', content: 'NaOH', isCorrect: false },
          { optionLabel: 'C', content: 'CH3COOH', isCorrect: true },
          { optionLabel: 'D', content: 'NaCl', isCorrect: false },
        ],
        correctAnswer: 'C',
        explanation: 'CH3COOH là axit yếu, phân li không hoàn toàn.',
      },
      {
        content: 'Theo Arrheniut, dung dịch có tính axit khi:',
        questionType: 'multiple-choice',
        difficulty: 'easy',
        points: 1,
        answers: [
          { optionLabel: 'A', content: '[H⁺] > [OH⁻]', isCorrect: true },
          { optionLabel: 'B', content: '[H⁺] < [OH⁻]', isCorrect: false },
          { optionLabel: 'C', content: '[H⁺] = [OH⁻]', isCorrect: false },
          { optionLabel: 'D', content: 'Không có H⁺', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'Dung dịch axit có nồng độ ion H⁺ lớn hơn nồng độ ion OH⁻.',
      },
      {
        content: 'Phương trình điện li nào sau đây sai?',
        questionType: 'multiple-choice',
        difficulty: 'medium',
        points: 1,
        answers: [
          { optionLabel: 'A', content: 'HCl → H⁺ + Cl⁻', isCorrect: false },
          { optionLabel: 'B', content: 'NaOH → Na⁺ + OH⁻', isCorrect: false },
          { optionLabel: 'C', content: 'CH3COOH → CH3COO⁻ + H⁺', isCorrect: true },
          { optionLabel: 'D', content: 'Na2SO4 → 2Na⁺ + SO4²⁻', isCorrect: false },
        ],
        correctAnswer: 'C',
        explanation: 'CH3COOH là chất điện li yếu, phải dùng mũi tên hai chiều: CH3COOH ⇌ CH3COO⁻ + H⁺',
      },
      {
        content: 'Cặp ion nào sau đây không cùng tồn tại trong dung dịch?',
        questionType: 'multiple-choice',
        difficulty: 'hard',
        points: 2,
        answers: [
          { optionLabel: 'A', content: 'Ba²⁺ và SO4²⁻', isCorrect: true },
          { optionLabel: 'B', content: 'Na⁺ và Cl⁻', isCorrect: false },
          { optionLabel: 'C', content: 'K⁺ và NO3⁻', isCorrect: false },
          { optionLabel: 'D', content: 'Na⁺ và SO4²⁻', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'Ba²⁺ và SO4²⁻ kết hợp tạo BaSO4 kết tủa nên không cùng tồn tại.',
      },
      {
        content: 'Cho phản ứng: H2SO4 + 2NaOH → Na2SO4 + 2H2O. Phương trình ion rút gọn là:',
        questionType: 'multiple-choice',
        difficulty: 'hard',
        points: 2,
        answers: [
          { optionLabel: 'A', content: 'H⁺ + OH⁻ → H2O', isCorrect: true },
          { optionLabel: 'B', content: '2H⁺ + 2OH⁻ → 2H2O', isCorrect: false },
          { optionLabel: 'C', content: 'H2SO4 + 2OH⁻ → SO4²⁻ + 2H2O', isCorrect: false },
          { optionLabel: 'D', content: 'SO4²⁻ + 2Na⁺ → Na2SO4', isCorrect: false },
        ],
        correctAnswer: 'A',
        explanation: 'Phương trình ion rút gọn đơn giản nhất: H⁺ + OH⁻ → H2O',
      },
    ],
  },
];
